# -*- coding: utf-8 -*-
"""Population_Growth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WB2veCFkvvSLm2IOjzwR3azeVp5ZCu3g
"""

import matplotlib.pyplot as plt
import numpy as np

# evenly sampled time at 200ms intervals
t = np.arange(0., 5., 0.2)

# red dashes, blue squares and green triangles
plt.plot(t, t, 'r--', t, t**2, 'bs-', t, t**3, 'g^:')
plt.show()

print(t)

print(t*100)

#[t, 500]

#print(type(t))
#t.append(500)

np.append(t,500)

time = np.arange(0., 100, 1)

print(time)

time = np.arange(0., 1000, 1)
grass = np.zeros_like(time)
rabbits = np.zeros_like(time)
foxes = np.zeros_like(time)

for t in range(time.shape[0]):
  if t==0:
    grass[0] = 100
    rabbits[0] = 4
    foxes[0] = 1
  else:
    grass[t] = 10 + grass[t-1] - rabbits[t-1]
    if grass[t] < 0:
      grass[t] = 0

    rabbits[t] = 1.05*rabbits[t-1] - 0.1*foxes[t-1]
    if rabbits[t] > grass[t]:
      rabbits[t] = grass[t]

    foxes[t] = 1.02*foxes[t-1]
    if 0.1*foxes[t] > rabbits[t]:
      foxes[t] = 0.1*rabbits[t]

plt.plot(time, grass, 'g--', time, rabbits, 'b-', time, foxes, 'r:')
plt.show()


